services:
  mongodb:
    image: mongo:latest
    container_name: shorten-url-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: shorten-url

volumes:
  mongodb_data:
